# Generated by Django 4.0.4 on 2022-09-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personagem',
            options={'verbose_name': 'Personagem', 'verbose_name_plural': 'Personagens'},
        ),
        migrations.AddField(
            model_name='personagem',
            name='recompensa',
            field=models.IntegerField(default=0, verbose_name='Recompensa'),
        ),
    ]
